const quarryImage = 'https://images.unsplash.com/photo-1573156667488-5c0cec674762?auto=format&fit=crop&w=1200&q=80';
const stoneSamplesImage = 'https://images.unsplash.com/photo-1749212387838-c4c4e6e58348?auto=format&fit=crop&w=1200&q=80';

export const quarries = [
  {
    id: 1,
    slug: 'gozgon-oq-marmar',
    name: "G'ozg'on oq marmar koni",
    type: 'Marmar',
    color: 'Oq',
    reserves: '85 mln m3',
    density: '2.7 g/sm3',
    location: "Navoiy viloyati, G'ozg'on shahri",
    description: "G'ozg'on hududidagi asosiy oq marmar yo'nalishlaridan biri.",
    fullDescription: "Bu sahifadagi zaxira va texnik ma'lumotlar MVP katalogi uchun indikator sifatida berilgan. Aniq geologik va tijoriy ma'lumotlar loyiha bo'yicha alohida tasdiqlanadi.",
    features: ['Oq rang', 'Jilolashga mos', 'Fasad va interyer uchun'],
    uses: ['Bezak plitkalar', 'Fasad', 'Yodgorliklar'],
    image: quarryImage,
    imageAlt: 'Ochiq marmar koni',
  },
  {
    id: 2,
    slug: 'gozgon-pushti-marmar',
    name: "G'ozg'on pushti marmar koni",
    type: 'Marmar',
    color: 'Pushti',
    reserves: '42 mln m3',
    density: '2.65 g/sm3',
    location: "Navoiy viloyati, G'ozg'on tumani",
    description: "Pushti tusli dekorativ marmar yo'nalishi.",
    fullDescription: "Bu sahifadagi zaxira va texnik ma'lumotlar MVP katalogi uchun indikator sifatida berilgan. Aniq geologik va tijoriy ma'lumotlar loyiha bo'yicha alohida tasdiqlanadi.",
    features: ['Pushti tus', "Dekorativ ko'rinish", 'Premium interyer uchun'],
    uses: ['Mehmonxonalar', 'Lobby zonalari', 'SPA interyerlari'],
    image: stoneSamplesImage,
    imageAlt: 'Rangli tabiiy tosh namunalari',
  },
  {
    id: 3,
    slug: 'gozgon-granit',
    name: "G'ozg'on granit koni",
    type: 'Granit',
    color: 'Kulrang',
    reserves: '120 mln m3',
    density: '2.8 g/sm3',
    location: "Navoiy viloyati, G'ozg'on shahri",
    description: "Kulrang va qoramtir granit yo'nalishi.",
    fullDescription: "Bu sahifadagi zaxira va texnik ma'lumotlar MVP katalogi uchun indikator sifatida berilgan. Aniq geologik va tijoriy ma'lumotlar loyiha bo'yicha alohida tasdiqlanadi.",
    features: ['Yuqori chidamlilik', 'Sovuqqa chidamli', 'Tashqi ishlar uchun'],
    uses: ['Fasad', 'Zinapoya', 'Yodgorliklar'],
    image: quarryImage,
    imageAlt: 'Tabiiy tosh qazib olinadigan kon',
  },
  {
    id: 4,
    slug: 'kulrang-marmar',
    name: 'Kulrang marmar koni',
    type: 'Marmar',
    color: 'Kulrang',
    reserves: '35 mln m3',
    density: '2.68 g/sm3',
    location: "Navoiy viloyati, G'ozg'on tumani",
    description: "Zamonaviy arxitekturada qo'llanadigan kulrang marmar yo'nalishi.",
    fullDescription: "Bu sahifadagi zaxira va texnik ma'lumotlar MVP katalogi uchun indikator sifatida berilgan. Aniq geologik va tijoriy ma'lumotlar loyiha bo'yicha alohida tasdiqlanadi.",
    features: ['Neytral rang', 'Minimal dizayn', "Ko'p qirrali qo'llanish"],
    uses: ['Ofis fasadlari', 'Minimal interyer', 'Restoran va savdo maydonlari'],
    image: stoneSamplesImage,
    imageAlt: 'Kulrang tosh namunalar',
  },
  {
    id: 5,
    slug: 'qizil-granit',
    name: 'Qizil granit koni',
    type: 'Granit',
    color: 'Qizil',
    reserves: '28 mln m3',
    density: '2.75 g/sm3',
    location: 'Navoiy viloyati',
    description: 'Qizil tusli granit dekorativ va monumental ishlarga mos.',
    fullDescription: "Bu sahifadagi zaxira va texnik ma'lumotlar MVP katalogi uchun indikator sifatida berilgan. Aniq geologik va tijoriy ma'lumotlar loyiha bo'yicha alohida tasdiqlanadi.",
    features: ['Aksent rang', 'Monumental ishlarga mos', 'Vaqtga chidamli'],
    uses: ['Yodgorliklar', 'Monumentlar', 'Landshaft bezagi'],
    image: quarryImage,
    imageAlt: 'Granit kon hududi',
  },
  {
    id: 6,
    slug: 'oltin-marmar',
    name: 'Oltin tusli marmar koni',
    type: 'Marmar',
    color: 'Oltin',
    reserves: '15 mln m3',
    density: '2.72 g/sm3',
    location: "Navoiy viloyati, G'ozg'on shahri",
    description: "Issiq oltin tusdagi dekorativ marmar yo'nalishi.",
    fullDescription: "Bu sahifadagi zaxira va texnik ma'lumotlar MVP katalogi uchun indikator sifatida berilgan. Aniq geologik va tijoriy ma'lumotlar loyiha bo'yicha alohida tasdiqlanadi.",
    features: ['Issiq rang', "Hashamatli ko'rinish", 'Premium segment'],
    uses: ['Premium mehmonxonalar', 'Galereyalar', 'Interyer aksentlari'],
    image: stoneSamplesImage,
    imageAlt: 'Oltin tusli tabiiy tosh namunalari',
  },
];

export const colors: Record<string, string> = {
  Oq: 'bg-gray-200 text-gray-800',
  Pushti: 'bg-pink-200 text-pink-900',
  Kulrang: 'bg-gray-400 text-white',
  Qizil: 'bg-red-600 text-white',
  Oltin: 'bg-yellow-400 text-yellow-900',
};

export const typeColors: Record<string, string> = {
  Marmar: 'bg-blue-500',
  Granit: 'bg-red-500',
};
